### ISSUE TITLE
Download Access Denied

### ISSUE THREAD

**Issue by neevshah101** [phil-mansfield/symphony#1]
I am trying to download all the halos in the MilkyWay suite, but I am facing this error for most of them. I was able to download most of them before, but I had deleted them and, for some reason, cannot download them again:

`
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1FLiC0L1TSnoMSpVhVOLsraqkuhREpTEv
`
What can I do to get around this error?

**Comment by phil-mansfield** [comment]
Ah, sorry about this. (And sorry about the late reply.) This is the result of Google secretly capping downloads to a single Drive account and then giving an incorrect error message. We're moving off Google Drive because of this. (Today, actually! In the process of making the branch now.)
